title: SENSHIN - 一意専心
description: SENSHIN アプリのサポートサイト
theme: minima
url: "https://blueblood1010.github.io"
baseurl: "/SENSHIN-support"

author:
  name: SENSHIN 開発チーム
  email: bb.singleminded@gmail.com
